services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      db:
        condition: service_healthy
    # command: ["./wait-for-postgres.sh", "db"]
    # entrypoint: ./wait-for-postgres.sh db:5432
  db:
    image: postgres
    ports:
      - "5050:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
      # - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql

volumes:
  dbdata: